#include <stdio.h>

#include "leds.h"
#include "test.h"

#include "display_analog.h"

#define MINS_IN_A_DAY 1440
// pos: 0 to 10800

#ifndef COUNTERCLOCKWISE
// clockwise
int hour_to_pos(int h, int m)
{
  int mins = h*60 + m;
  // char b[256];
  // sprintf(b, "1: %d %d %d\n", h, m, mins);
  // print(b);
  return ((mins+MINS_IN_A_DAY/2)%MINS_IN_A_DAY)*(POS_IN_A_TURN/MINS_IN_A_DAY); // clockwise
}

// Array of the discreet hands positions.
// It is precompiled and optimized so please dont freak out when seeing it as it is now
int m_to_p[60] = {
  ((POS_IN_A_TURN/60)*0+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*1+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*2+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*3+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*4+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*5+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*6+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*7+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*8+POS_IN_A_TURN/2)%POS_IN_A_TURN,
  ((POS_IN_A_TURN/60)*9+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*10+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*11+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*12+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*13+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*14+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*15+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*16+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*17+POS_IN_A_TURN/2)%POS_IN_A_TURN,
  ((POS_IN_A_TURN/60)*18+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*19+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*20+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*21+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*22+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*23+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*24+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*25+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*26+POS_IN_A_TURN/2)%POS_IN_A_TURN,
  ((POS_IN_A_TURN/60)*27+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*28+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*29+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*30+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*31+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*32+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*33+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*34+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*35+POS_IN_A_TURN/2)%POS_IN_A_TURN,
  ((POS_IN_A_TURN/60)*36+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*37+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*38+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*39+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*40+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*41+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*42+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*43+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*44+POS_IN_A_TURN/2)%POS_IN_A_TURN,
  ((POS_IN_A_TURN/60)*45+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*46+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*47+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*48+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*49+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*50+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*51+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*52+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*53+POS_IN_A_TURN/2)%POS_IN_A_TURN,
  ((POS_IN_A_TURN/60)*54+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*55+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*56+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*57+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*58+POS_IN_A_TURN/2)%POS_IN_A_TURN, ((POS_IN_A_TURN/60)*59+POS_IN_A_TURN/2)%POS_IN_A_TURN
};
#else
// counterclockwise
int hour_to_pos(int h, int m)
{
  int mins = h*60 + m;
  // char b[256];
  // sprintf(b, "1: %d %d %d\n", h, m, mins);
  // print(b);
  return POS_IN_A_TURN - ((mins+MINS_IN_A_DAY/2)%MINS_IN_A_DAY)*(POS_IN_A_TURN/MINS_IN_A_DAY); // clockwise
}

// Array of the discreet hands positions.
// It is precompiled and optimized so please dont freak out when seeing it as it is now
int m_to_p[60] = {
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*0+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*1+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*2+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*3+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*4+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*5+POS_IN_A_TURN/2)%POS_IN_A_TURN),
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*6+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*7+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*8+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*9+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*10+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*11+POS_IN_A_TURN/2)%POS_IN_A_TURN),
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*12+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*13+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*14+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*15+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*16+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*17+POS_IN_A_TURN/2)%POS_IN_A_TURN),
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*18+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*19+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*20+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*21+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*22+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*23+POS_IN_A_TURN/2)%POS_IN_A_TURN),
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*24+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*25+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*26+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*27+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*28+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*29+POS_IN_A_TURN/2)%POS_IN_A_TURN),
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*30+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*31+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*32+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*33+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*34+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*35+POS_IN_A_TURN/2)%POS_IN_A_TURN),
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*36+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*37+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*38+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*39+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*40+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*41+POS_IN_A_TURN/2)%POS_IN_A_TURN),
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*42+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*43+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*44+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*45+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*46+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*47+POS_IN_A_TURN/2)%POS_IN_A_TURN),
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*48+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*49+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*50+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*51+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*52+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*53+POS_IN_A_TURN/2)%POS_IN_A_TURN),
  POS_IN_A_TURN - (((POS_IN_A_TURN/60)*54+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*55+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*56+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*57+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*58+POS_IN_A_TURN/2)%POS_IN_A_TURN), POS_IN_A_TURN - (((POS_IN_A_TURN/60)*59+POS_IN_A_TURN/2)%POS_IN_A_TURN)
};

#endif

int minute_to_pos(int m, int s)
{
  return m_to_p[m];
}

int seconds_to_pos(int s)
{
  return m_to_p[s];
}

// cw
uint16_t get_hands(int pos, int h_pos, int m_pos, int s_pos)
{
  uint16_t leds = LEDS_OFF;
  if(pos == h_pos)
    leds |= HOUR_HAND;
  if(pos == m_pos)
    leds |= MINUTE_HAND;
  #ifndef COUNTERCLOCKWISE
  if((seconds < 30  &&  pos >= POS_IN_A_TURN/2 && pos <= s_pos)
  || (seconds >= 30 && (pos >= POS_IN_A_TURN/2 || pos <= s_pos)))
  #else
  if((seconds < 30  &&  pos <= POS_IN_A_TURN/2 && pos >= s_pos)
  || (seconds >= 30 && (pos <= POS_IN_A_TURN/2 || pos >= s_pos)))
  #endif
    leds |= SECOND_HAND;

  // char b[256];
  // sprintf(b, "%02d:%02d:%02d\n%d %d %d\n%04x\n", hours, minutes, seconds, hour_to_pos(hours, minutes), minute_to_pos(minutes, seconds), seconds_to_pos(seconds), leds);
  // print(b);
  return leds;
}

uint16_t display[POS_IN_A_TURN];

void compute_display() {
  int h_pos = hour_to_pos(hours, minutes);
  int m_pos = minute_to_pos(minutes, seconds);
  int s_pos = seconds_to_pos(seconds);
  for(int pos = 0; pos < POS_IN_A_TURN; pos++){
    display[pos] = get_hands(pos, h_pos, m_pos, s_pos);
  }
}

void display_strip()
{
  int pos = get_arc_min();
  leds_on(display[pos]);
}
